<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Lakshmi" failures="1" tests="7" name="practice.Listener.ListerRetryTest" time="0.038" errors="0" timestamp="2024-06-17T13:27:38 IST" skipped="4">
  <testcase classname="practice.Listener.ListerRetryTest" name="configTest1" time="0.005">
    <skipped/>
  </testcase> <!-- configTest1 -->
  <testcase classname="practice.Listener.ListerRetryTest" name="configTest1" time="0.002">
    <failure message="Test1 failed" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test1 failed
at practice.Listener.ListerRetryTest.configTest1(ListerRetryTest.java:11)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- configTest1 -->
  <testcase classname="practice.Listener.ListerRetryTest" name="configTest1" time="0.022">
    <skipped/>
  </testcase> <!-- configTest1 -->
  <testcase classname="practice.Listener.ListerRetryTest" name="configTest3" time="0.003"/>
  <testcase classname="practice.Listener.ListerRetryTest" name="configTest2" time="0.001"/>
  <testcase classname="practice.Listener.ListerRetryTest" name="configTest1" time="0.002">
    <skipped/>
  </testcase> <!-- configTest1 -->
  <testcase classname="practice.Listener.ListerRetryTest" name="configTest1" time="0.003">
    <skipped/>
  </testcase> <!-- configTest1 -->
</testsuite> <!-- practice.Listener.ListerRetryTest -->
